import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Heading,
  Text,
  Section,
} from "@react-email/components";
import * as React from "react";

export default function BrandEmail({ brandData }) {
  return (
    <Html>
      <Head />
      <Preview>New Brand Query from {brandData.brand}</Preview>
      <Body style={{ backgroundColor: "#f9fafb", fontFamily: "Arial, sans-serif" }}>
        <Container
          style={{
            margin: "20px auto",
            padding: "20px",
            backgroundColor: "#ffffff",
            borderRadius: "12px",
            boxShadow: "0 4px 8px rgba(0,0,0,0.05)",
            maxWidth: "600px",
          }}
        >
          <Heading style={{ color: "#111827", fontSize: "20px", marginBottom: "10px" }}>
            📢 New Brand Query
          </Heading>
          <Text style={{ color: "#374151", marginBottom: "20px" }}>
            A new brand has submitted their details. Here are the details:
          </Text>

          <Section style={{ marginBottom: "10px" }}>
            <Text><strong>Brand:</strong> {brandData.brand}</Text>
            <Text><strong>Email:</strong> {brandData.email}</Text>
            <Text><strong>Phone:</strong> {brandData.phoneNo}</Text>
            <Text><strong>Budget:</strong> ${brandData.budget}</Text>
            <Text><strong>Description:</strong> {brandData.description}</Text>
          </Section>

          <Section style={{ marginBottom: "10px" }}>
            <Text><strong>Platforms:</strong> {brandData.platforms.join(", ")}</Text>
            <Text><strong>Campaign Goals:</strong> {brandData.campaign.join(", ")}</Text>
            <Text><strong>Content Types:</strong> {brandData.content.join(", ")}</Text>
            <Text><strong>Industry:</strong> {brandData.industry.join(", ")}</Text>
          </Section>

          <Text style={{ color: "#6b7280", fontSize: "12px", marginTop: "20px" }}>
            — This email was automatically generated by Growwik Brand Page Form
          </Text>
        </Container>
      </Body>
    </Html>
  );
}
