// emails/InfluencerEmail.jsx
import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Heading,
  Text,
  Section,
} from "@react-email/components";
import * as React from "react";

export default function InfluencerEmail({ influencerData }) {
  return (
    <Html>
      <Head />
      <Preview>New Influencer Signup - {influencerData.name}</Preview>
      <Body
        style={{
          backgroundColor: "#f9fafb",
          fontFamily: "Arial, sans-serif",
        }}
      >
        <Container
          style={{
            margin: "20px auto",
            padding: "20px",
            backgroundColor: "#ffffff",
            borderRadius: "12px",
            boxShadow: "0 4px 8px rgba(0,0,0,0.05)",
            maxWidth: "600px",
          }}
        >
          <Heading
            style={{
              color: "#111827",
              fontSize: "20px",
              marginBottom: "10px",
            }}
          >
            🎉 New Influencer Signup
          </Heading>

          <Text style={{ color: "#374151", marginBottom: "20px" }}>
            A new influencer has registered. Here are the details:
          </Text>

          <Section style={{ marginBottom: "10px" }}>
            <Text>
              <strong>Name:</strong> {influencerData.name}
            </Text>
            <Text>
              <strong>Email:</strong> {influencerData.email}
            </Text>
            <Text>
              <strong>Phone:</strong> {influencerData.phoneNo}
            </Text>
            <Text>
              <strong>Instagram ID:</strong> {influencerData.instaId}
            </Text>
            <Text>
              <strong>YouTube ID:</strong> {influencerData.youtubeId}
            </Text>
            <Text>
              <strong>Followers:</strong> {influencerData.followersCount}
            </Text>
          </Section>

          <Section style={{ marginBottom: "10px" }}>
            <Text>
              <strong>Platforms:</strong>{" "}
              {influencerData.platforms.join(", ")}
            </Text>
            <Text>
              <strong>Genres:</strong> {influencerData.genre.join(", ")}
            </Text>
          </Section>

          <Text
            style={{
              color: "#6b7280",
              fontSize: "12px",
              marginTop: "20px",
            }}
          >
            — This email was automatically generated by Growwik Influencer Page
          </Text>
        </Container>
      </Body>
    </Html>
  );
}
