// emails/UserEmail.jsx
import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Heading,
  Text,
  Section,
} from "@react-email/components";
import * as React from "react";

export default function UserEmail({ userData }) {
  return (
    <Html>
      <Head />
      <Preview>New User Request - {userData.name}</Preview>
      <Body
        style={{
          backgroundColor: "#f9fafb",
          fontFamily: "Arial, sans-serif",
        }}
      >
        <Container
          style={{
            margin: "20px auto",
            padding: "20px",
            backgroundColor: "#ffffff",
            borderRadius: "12px",
            boxShadow: "0 4px 8px rgba(0,0,0,0.05)",
            maxWidth: "600px",
          }}
        >
          <Heading
            style={{
              color: "#111827",
              fontSize: "20px",
              marginBottom: "10px",
            }}
          >
            📩 New User Request
          </Heading>

          <Text style={{ color: "#374151", marginBottom: "20px" }}>
            You’ve received a new message from a user. Here are the details:
          </Text>

          <Section style={{ marginBottom: "10px" }}>
            <Text>
              <strong>Name:</strong> {userData.name}
            </Text>
            <Text>
              <strong>Company:</strong> {userData.company}
            </Text>
            <Text>
              <strong>Email:</strong> {userData.email}
            </Text>
            <Text>
              <strong>Contact:</strong> {userData.contact}
            </Text>
          </Section>

          <Section
            style={{
              marginTop: "20px",
              padding: "15px",
              backgroundColor: "#f3f4f6",
              borderRadius: "8px",
            }}
          >
            <Text style={{ marginBottom: "5px", fontWeight: "bold" }}>
              Message:
            </Text>
            <Text>{userData.message}</Text>
          </Section>

          <Text
            style={{
              color: "#6b7280",
              fontSize: "12px",
              marginTop: "20px",
            }}
          >
            — This email was automatically generated by Growwik Contact Page
          </Text>
        </Container>
      </Body>
    </Html>
  );
}
